CREATE TABLE category (
                          id      INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name    VARCHAR(255) NOT NULL
);

CREATE TABLE product (
                         id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         category_id INT REFERENCES category (id) ON DELETE SET NULL,
                         name        VARCHAR(255) NOT NULL,
                         description TEXT,
                         price       NUMERIC(10, 2) NOT NULL
);

INSERT INTO category(name)
VALUES ('Electronics'),
       ('Home'),
       ('Sports'),
       ('Clothing'),
       ('Shoes'),
       ('Books');

INSERT INTO product(category_id, name, description, price)
VALUES (1, 'Ca2a Vinci Code', 'The best book for your daily reading', 19.99);
